---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/tag.init: regexp:^3.*
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      $setElementOrder/initContainers:
      - name: init
      containers:
      - image: stefanprodan/podinfo:4.0.5
        name: podinfod
      initContainers:
      - image: alpine:3
        name: init
